networks:
  # Network for controller <-> switch communication
  sdn_net:
    driver: bridge
  # Virtual "cable" between host1 and the switch
  link-h1-s1:
    driver: bridge
  # Virtual "cable" between host2 and the switch
  link-h2-s1:
    driver: bridge

services:
  ryu:
    build:
      context: .
      dockerfile: Dockerfile.ryu
    image: cyber-range/ryu
    container_name: ryu-controller
    networks:
      - sdn_net
    ports:
      - "6633:6633"
      - "8080:8080"
    restart: on-failure

  ovs1:
    build:
      context: .
      dockerfile: Dockerfile.ovs
    image: cyber-range/ovs
    container_name: ovs-switch1
    privileged: true
    depends_on:
      - ryu
    networks:
      - sdn_net
      - link-h1-s1
      - link-h2-s1
    command: /ovs-setup.sh

  h1:
    image: busybox:latest
    container_name: host1
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    depends_on:
      - ovs1
    networks:
      - link-h1-s1

  h2:
    image: busybox:latest
    container_name: host2
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    depends_on:
      - ovs1
    networks:
      - link-h2-s1